# Eksempel på epostgrupper: 
test: [ henrik@domene.no, henrik.ormasen@domene.no ]
testgruppe2: [ henrik@domene.no ]
testgruppe2: [ henrik@domene.no ]
asdf

ledelsen: [ henrik@tjen-folket.no ]
materiell: [ henrik@tjen-folket.no ]











