--- 
AdminController: 
  new: 
  usernyttpass: 
  list: 
  usershow: 
  userlist: 
  userupdate: 
  edit: 
  destroy: 
  create: 
  index: Admin
  show: 
  userdestroy: 
  update: 
  useredit: 
PresseController: 
  sender: 
  index: Writers
  bekreft: 
StylesheetsController: 
  component_update: 
  component: 
  new: 
  list: 
  edit: 
  destroy: 
  cancel: 
  create: 
  show: 
  index: Admin
  return_to_main: 
  update: 
Role2groupController: 
  list: 
  groups: 
  edit: 
  index: Admin
  show: 
  update: 
ImagesController: 
  new: Writers
  edit: Writers
  destroy: Writers
  create: Writers
  index: bildesjef
  update: Writers
  clean: 
AccountController: 
  forgot_password: 
  logout: 
  reset_password: 
  signup: 
  index: 
  activate: 
  login: 
LagController: 
  list: test
  index_old: 
  index: RoleAdmin or UserAdmin
  show: test2
  lag: 
  lag_old: 
  no_lag: 
  asker: 
LagAdminController: 
  au: 
  asker: 
ArticlesController: 
  new: 
  auto_complete_responder_for_group: 
  list: 
  un_publish: 
  hide: 
  parse_textile: 
  edit: 
  html2textile: 
  destroy: 
  createRAILS: 
  create_new_common: 
  create: 
  auto_complete_for_autogroup_name: 
  savemiu: 
  legginntemaer: 
  articles: 
  index: Writers
  show: 
  temaboksen: 
  say_hello: 
  publish: 
  clothsyntaxmenue: 
  update: 
  clear_item: 
  troll: 
  toiso: 
LagArticlesController: 
  new: 
  list: 
  un_publish: 
  edit: 
  destroy: 
  create: 
  articles: 
  index: 
  show: 
  publish: 
  update: 
  clear_item: 
GroupMembersController: 
  new: 
  list: 
  edit: 
  destroy: 
  create: 
  index: 
  show: 
  update: 
SendpostController: 
  lagreyml: Admin
  zip_file: Admin
  admin: Admin
  lagre: Admin
  sfp: Admin
  index: Admin
ApplicationController: 
  group_from_name: 
  norinitialize: 
  creator: 
  authorized_to: 
  list_item: 
  updater: 
  sql: 
  find_item: 
  initialize: 
  article_from_name: 
  emailreg: 
  apphelp: 
  left_column: 
  del_item: 
  groups_select: 
  markitupp: 
  set_charset: 
  users_select: 
  authorized: 
  add_item: 
GroupsController: 
  auto_complete_responder_for_group: 
  temaer: 
  new: 
  slett: 
  list: 
  felles: 
  edit: 
  destroy: 
  move: 
  create: 
  index: writer
  show: 
  home: 
  update: 
ArticleGroupsController: 
  new: 
  list: 
  edit: 
  destroy: 
  create: 
  index: 
  show: 
  update: 
RailStatController: 
  hits: 
  platform: 
  refs: 
  track: 
  index: 
  lang: 
  path: 
  other: 
  tracker_js: 
  extract_subdomain: 
ListerController: 
  variabler: 
  list: 
  add: 
  innmeld: 
  norusers2list: 
  index: lister
  avmeld: 
StartController: 
  sql_from_only_one_group: 
  search: 
  topplinker: 
  sql: 
  right_column: 
  advertisement: 
  initialize: 
  after: 
  print: 
  show: 
  venstre_meny: 
  bunntekst: 
  group: 
  view: 
  search_result: 
  before: 
GroupGroupsController: 
  new: 
  list: 
  edit: 
  destroy: 
  create: 
  index: 
  show: 
  update: 
ArticleMembersController: 
  new: 
  list: 
  edit: 
  destroy: 
  create: 
  index: 
  show: 
  update: 
