sprak: [ trond.thorbjornsen@sos-rasisme.no, jan.erik.skretteberg@sos-rasisme.no ]
buttons: [ simen.ulven.seipajervi@sos-rasisme.no, trond.thorbjornsen@sos-rasisme.no, ou@sos-rasisme.no ]
soppel: [ spam@sos-rasisme.no, tthorb@gmail.com]

test: [ henrik@domene.no, henrik.ormasen@domene.no ]
testgruppe2: [ henrik@domene.no ]
<<<<<<< HEAD
llk: [ ou@sos-rasisme.no, au@sos-rasisme.no, bjarne.stokke@sos-rasisme.no, trond.thorbjornsen@sos-rasisme.no, baard.frantzen@sos-rasisme.no, kenneth.fuglemsmo@sos-rasisme.no, henrik.ormasen@sos-rasisme.no ]
innmeldingsskjema: [ medlemskap.liste@sos-rasisme.no ]

billettbestilling: [ hovedkasserer@sos-rasisme.no, trond.thorbjornsen@sos-rasisme.no, bjarne.stokke@sos-rasisme.no ]

materiell: [ hovedkasserer@sos-rasisme.no, ou@sos-rasisme.no, bizhan.shibani@sos-rasisme.no, henrik@sos-rasisme.no ]
antirasisten: [ jan.erik.skretteberg@sos-rasisme.no ]
fuogeli: [ fu@sos-rasisme.no, bizhan.shibani@sos-rasisme.no ]
fakkel: [ fakkel.liste@sos-rasisme.no ]
kurdisk: [ idris.sabir.aziz@sos-rasisme.no ]
antinazi: [ antinazi@sos-rasisme.no ]
jakkemerker: [ hovedkasserer@sos-rasisme.no, bizhan.shibani@sos-rasisme.no  ]
tthk: [ trond.thorbjornsen@sos-rasisme.no, hovedkasserer@sos-rasisme.no ]
avin: [ trond.thorbjornsen@sos-rasisme.no ]
lm2010: [ au@sos-rasisme.no, trond.thorbjornsen@sos-rasisme.no, henrik@sos-rasisme.no ]
lm2008: [ lm2008@sos-rasisme.no ]
lm2006: [ lm2008@sos-rasisme.no ]
papir: [ bizhan.shibani@sos-rasisme.no, papir@sos-rasisme.no ]
auou: [ au@sos-rasisme.no, ou@sos-rasisme.no ]
auoubjarne: [ bjarne.stokke@sos-rasisme.no, au@sos-rasisme.no, ou@sos-rasisme.no ]

kampanjebestilling: [ au@sos-rasisme.no ]

medlemskap: [ ou@sos-rasisme.no, trond.thorbjornsen@sos-rasisme.no, benedikte.lovli@sos-rasisme.no ]
medlemskap-fu: [ ou@sos-rasisme.no, trond.thorbjornsen@sos-rasisme.no, benedikte.lovli@sos-rasisme.no, fu@sos-rasisme.no ]

oslo: [ trond.thorbjornsen@sos-rasisme.no, nasim.ahzami@sos-rasisme.no ]
orgu: [ ou@sos-rasisme.no, trond.thorbjornsen@sos-rasisme.no ]

testsvarepost: [ trond.thorbjornsen@sos-rasisme.no ]

rkmeraker: [ trond.thorbjornsen@sos-rasisme.no, anders.eikeland@sos-rasisme.no, hogne.ormasen@sos-rasisme.no ]
rksandvika: [ ola.melbye.pettersen@sos-rasisme.no, benedikte.lovli@sos-rasisme.no, renate.lehne@sos-rasisme.no, trond.thorbjornsen@sos-rasisme.no ]
rkoslo: [ benedikte.lovli@sos-rasisme.no, trond.thorbjornsen@sos-rasisme.no ]
rkvestfold: [ christiane.walther.muribo@sos-rasisme.no, iselin.knudsen.saeterdal@sos-rasisme.no ]
rkost: [ benedikte.lovli@sos-rasisme.no, baard.frantzen@sos-rasisme.no, jan.erik.skretteberg@sos-rasisme.no, jon.trygve.bergsaker@sos-rasisme.no, trond.thorbjornsen@sos-rasisme.no, runar.engja@sos-rasisme.no, simen.ulven.seipajervi@sos-rasisme.no, lill.mari.mundal@sos-rasisme.no ]

region-nn: [ henrik.ormasen@sos-rasisme.no, lill.mari.bjornvik.mundal@sos-rasisme.no ]

salem: [ baard.frantzen@sos-rasisme.no, hovedkasserer@sos-rasisme.no, henrik.ormasen@sos-rasisme.no, trond.thorbjornsen@sos-rasisme.no ]
orgu: [ trond.thorbjornsen@sos-rasisme.no, ou@sos-rasisme.no ]
sos: [ paal.austad.solfjeld@sos-rasisme.no, au@sos-rasisme.no ]
tips: [ tips@sos-rasisme.no ]
etiketter: [ hovedkasserer@sos-rasisme.no, bjarne.stokke@sos-rasisme.no ]
tips-k: [ baard.frantzen@sos-rasisme.no, trond.thorbjornsen@sos-rasisme.no, hovedkasserer@sos-rasisme.no, jan.erik.skretteberg@sos-rasisme.no ]
rapport-k: [ trond.thorbjornsen@sos-rasisme.no, christiane.walther.muriboe@sos-rasisme.no, hovedkasserer@sos-rasisme.no ]
od: [ hovedkasserer@sos-rasisme.no ]

17mfa: [ benedikte.lovli@sos-rasisme.no, sondre.saebjornsen@sos-rasisme.no, baard.frantzen@sos-rasisme.no, hakon.bjorgo@sos-rasisme.no, hovedkasserer@sos-rasisme.no, simen.ulven.seipajervi@sos-rasisme.no, trond.thorbjornsen@sos-rasisme.no, henrik.ormasen@sos-rasisme.no ]

Debatt: [ ola.melbye.pettersen@sos-rasisme.no, trond.thorbjornsen@sos-rasisme.no ]

krystallnatta: [ christiane.walther.muribo@sos-rasisme.no, benedikte.lovli@sos-rasisme.no, ou@sos-rasisme.no, au@sos-rasisme.no, bizhan.shibani@sos-rasisme.no ]

avinst: [ henrik.ormasen@sos-rasisme.no ]

populus: [ henrik.ormasen@sos-rasisme.no ] 
populus2: [ henrik.ormasen@sos-rasisme.no ] 
aktivistno: [ henrik.ormasen@sos-rasisme.no, joakim.langvand@sos-rasisme.no ] 

=======
ledelsen: [ post@tjen-folket.no ]
materiell: [ per@tjen-folket.no, post@tjen-folket.no ]
sommerleir: [ sommerleir2010@tjen-folket.no, post@tjen-folket.no ]
rapport: [ isak@tjen-folket.no, glenn@tjen-folket.no, asbjorn@tjen-folket.no, alfred@tjen-folket.no, andre@tjen-folket.no ]
>>>>>>> d855e6e56203cc9a8c33d77148a72495b842a6e3
