# Eksempel på epostgrupper: 
test: [ henrik@domene.no, henrik.ormasen@domene.no ]
testgruppe2: [ henrik@domene.no ]
ledelsen: [ post@tjen-folket.no ]
materiell: [ per@tjen-folket.no, post@tjen-folket.no ]
sommerleir: [ sommerleir2010@tjen-folket.no, post@tjen-folket.no ]
rapport: [ isak@tjen-folket.no, glenn@tjen-folket.no, asbjorn@tjen-folket.no, alfred@tjen-folket.no, andre@tjen-folket.no ]





